# Generated by Django 2.0.1 on 2018-11-20 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('app_package', models.CharField(blank=True, max_length=255, null=True)),
                ('app_activity', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('app_version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('udid', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField()),
                ('static_ip', models.CharField(blank=True, max_length=25, null=True)),
                ('so_version', models.CharField(blank=True, max_length=25, null=True)),
                ('client_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.ClientApp')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='devices.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DevicesPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('appium_port', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('app_packages', models.ManyToManyField(to='devices.AppPackage')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.ManyToManyField(to='devices.DevicesPlatform'),
        ),
    ]
