# Generated by Django 2.0.1 on 2018-11-21 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20181121_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appversions', to='devices.DevicesPlatform')),
            ],
        ),
        migrations.AlterField(
            model_name='clientapp',
            name='app_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='devices.AppVersion'),
        ),
    ]
