# Generated by Django 2.0.1 on 2018-11-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20181121_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientapp',
            name='app_version',
        ),
        migrations.AddField(
            model_name='clientapp',
            name='app_version',
            field=models.ManyToManyField(to='devices.AppVersion'),
        ),
    ]
