# Generated by Django 2.0.1 on 2018-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Activa')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='tour',
            name='type_tour',
            field=models.CharField(choices=[('_Nav', 'Navigation'), ('', 'AppMobile')], default='', max_length=6, verbose_name='types'),
        ),
    ]
