# Generated by Django 2.0.1 on 2018-11-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20181121_0420'),
        ('tours', '0002_auto_20181121_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tour', models.CharField(choices=[('_Nav', 'Navigation'), ('_', 'AppMobile')], default='_', max_length=6, verbose_name='types')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Activa')], default=1, verbose_name='status')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='devices.Device')),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='type_tour',
        ),
        migrations.AlterField(
            model_name='step',
            name='tour_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tours.TourDevice'),
        ),
        migrations.AddField(
            model_name='tourdevice',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.Tour'),
        ),
    ]
